version: 0.0 
os: linux 
files: 
  - source: / 
    destination: /usr/share/nginx/html/  
# HTML 파일을 복사할 배포할 웹 서버의 경로 
hooks: 
  BeforeInstall: 
    - location: scripts/before_install.sh 
      timeout: 300 
      runas: root 
  AfterInstall: 
    - location: scripts/update_metadata.sh 
      timeout: 300 
      runas: root